import "./globals.css";
// import Link from "next/link";
// import { useRouter } from "next/navigation";

import { Header } from "@/components/Header";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Loading = () => {
  return <div>Loading... Ajillaj bn </div>;
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white">
        <Header />

        {children}
      </body>
    </html>
  );
}
